[workspace]
authors = ["lorenzo <lorenzo.cerrone@uzh.ch>"]
channels = ["conda-forge"]
name = "fractal-pixi-compose"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[activation.env]
# postgres and backend
PGDATA = "$PIXI_PROJECT_ROOT/local/postgres/data"
POSTGRES_DB = "fractaldb"
POSTGRES_HOST = "localhost"
POSTGRES_USER = "fractal"
POSTGRES_PORT = "5433"
POSTGRES_PASSWORD = "fractal"
ADMIN_EMAIL = "admin@example.org"
ADMIN_PWD = "1234"
ADMIN_PROJECT_DIR = "$PIXI_PROJECT_ROOT/local/project_dir"
JWT_SECRET_KEY = "local-dev-secret-change-me"
FRACTAL_RUNNER_BACKEND = "local"
FRACTAL_DEFAULT_GROUP_NAME = "All"
JWT_EXPIRE_SECONDS = "84600"
FRACTAL_LOGGING_LEVEL = "20"
# frontend
FRACTAL_WEB_DIR = "$PIXI_PROJECT_ROOT/local/fractal-web"
FRACTAL_WEB_VERSION = "v1.27.4"

FRACTAL_SERVER_HOST = "http://127.0.0.1:8000"
ORIGIN = "http://localhost:5173"
# PORT = "5173"
AUTH_COOKIE_DOMAIN = "localhost"
# Required for HTTP (non-HTTPS) local dev; set to true when behind TLS
AUTH_COOKIE_SECURE = "false"
PUBLIC_FRACTAL_ADMIN_SUPPORT_EMAIL = "admin@example.org"
BODY_SIZE_LIMIT = "5000000"



# CLI client
FRACTAL_SERVER = "http://localhost:8000"
FRACTAL_USER = "admin@example.org"
FRACTAL_PASSWORD = "1234"

[feature.orchestrator.dependencies]
process-compose = "*"

[feature.frontend.dependencies]
nodejs = ">=24.0, <25.0"

[feature.backend.dependencies]
postgresql = ">=18.0,<19.0"

[feature.backend.pypi-dependencies]
fractal-server = "==2.22.5"
# fractal-server = {path = "../fractal-server", editable = true}

[feature.cli-client.pypi-dependencies]
fractal-client = "==2.20.1"


[feature.py11.dependencies]
python = "==3.11"
[feature.py12.dependencies]
python = "==3.12"
[feature.py13.dependencies]
python = "==3.13"
[feature.py14.dependencies]
python = "==3.14"

[tasks.db-setup]
depends-on = ["db-cleanup"]
cmd = """
mkdir -p $PGDATA && \
initdb -D $PGDATA --no-locale --encoding=UTF8 --username=$POSTGRES_USER --auth=trust && \
pg_ctl -o '-p $POSTGRES_PORT' -D $PGDATA -l $PIXI_PROJECT_ROOT/local/postgres/logfile start && \
createdb -p $POSTGRES_PORT -h $POSTGRES_HOST -U $POSTGRES_USER $POSTGRES_DB
"""

[tasks.db-stop]
cmd = "pg_ctl -o '-p $POSTGRES_PORT' status -D $PGDATA && pg_ctl -o '-p $POSTGRES_PORT' -D $PGDATA stop || true"

[tasks.db-cleanup]
depends-on = ["db-stop"]
cmd = "rm -rf $PGDATA"

[tasks.backend-prepare-resource]
cmd = "python $PIXI_PROJECT_ROOT/scripts/build_resources.py"

[tasks.backend-set-db]
depends-on = ["db-setup", "backend-prepare-resource"]
cmd = "fractalctl set-db"

[tasks.backend-setup]
depends-on = ["backend-set-db"]
cmd = """
fractalctl init-db-data \
    --admin-email $ADMIN_EMAIL --admin-pwd $ADMIN_PWD \
    --admin-project-dir $ADMIN_PROJECT_DIR \
    --profile default \
    --resource $PIXI_PROJECT_ROOT/local/resources.json
"""

[tasks.backend-start]
cmd = "fractalctl start --host 0.0.0.0 -p 8000"

[tasks.backend-cleanup]
cmd = "rm -rf local/data-jobs local/data-tasks"

[tasks.frontend-setup]
cmd = """
rm -rf $FRACTAL_WEB_DIR && \
mkdir -p $FRACTAL_WEB_DIR && \
git clone https://github.com/fractal-analytics-platform/fractal-web $FRACTAL_WEB_DIR && \
git -C $FRACTAL_WEB_DIR checkout $FRACTAL_WEB_VERSION && \
cd $FRACTAL_WEB_DIR && \
rm -f .env .env.development .env.local && \
npm install
"""

[tasks.frontend-start]
cmd = "npm run dev --prefix $FRACTAL_WEB_DIR"

[tasks.frontend-cleanup]
cmd = "rm -rf $FRACTAL_WEB_DIR"

[tasks.setup]
depends-on = ["backend-setup", "frontend-setup"]

[tasks.cleanup]
depends-on = ["db-cleanup", "backend-cleanup", "frontend-cleanup"]


[tasks.collect-fractal-tasks-mock]
cmd = """
wget --quiet -O local/fractal_tasks_mock-0.0.1-py3-none-any.whl https://github.com/fractal-analytics-platform/fractal-server/raw/e0a3ca44f521fe622cf1d3a09d3e5058b096c6f2/tests/v2/fractal_tasks_mock/dist/fractal_tasks_mock-0.0.1-py3-none-any.whl && \
fractal task collect ./local/fractal_tasks_mock-0.0.1-py3-none-any.whl
"""

[tasks.collect-fractal-tasks-core]
cmd = "fractal task collect fractal-tasks-core --package-version 2.0.0"

[tasks.collect-fractal-uzh-converters]
cmd = "fractal task collect fractal-uzh-converters --package-version 0.5.0"


[feature.napari-ome-zarr.pypi-dependencies]
napari = { "extras" = ["all"], version = "<0.7" }
napari-ome-zarr-navigator = ">=0.2.4, <0.3"
napari-ome-zarr = ">=0.6.1, <0.7"
napari-feature-classifier = ">=0.3.2, <0.4"
napari-feature-visualization = ">=0.0.2, <0.0.3"

[feature.napari-ome-zarr.tasks]
napari-ome-zarr = "napari"

[environments]
default = ["py13", "backend", "frontend", "orchestrator", "cli-client"]
py11 = ["py11"]
py12 = ["py12"]
py13 = ["py13"]
py14 = ["py14"]
napari-ome-zarr = ["py13", "napari-ome-zarr"]
