version: "0.5"

processes:
  fractal-server:
    command: pixi run -e backend backend-start
    description: "fractal-server on http://localhost:8000"
    readiness_probe:
      initial_delay_seconds: 1
      period_seconds: 2
      http_get:
        host: localhost
        port: 8000
        path: /api/alive/

  fractal-web:
    command: pixi run -e frontend frontend-start
    description: "fractal-web on http://localhost:5173"
    depends_on:
      fractal-server:
        condition: process_healthy
    readiness_probe:
      initial_delay_seconds: 1
      period_seconds: 2
      http_get:
        host: localhost
        port: 5173
        path: /alive
  
  fractal-data:
    command: pixi run -e data data-start
    description: "fractal-data on http://localhost:3000"
    depends_on:
      fractal-server:
        condition: process_healthy
  
  fractal-feature-explorer:
    command: pixi run -e explorer explorer-start
    description: "fractal-feature-explorer on http://localhost:8501"
    depends_on:
      fractal-server:
        condition: process_healthy

  fractal-tasks-core:
    command: pixi run -e cli-client collect-fractal-tasks-core
    description: "Trigger collection of fractal-tasks-core"
    depends_on:
      fractal-server:
        condition: process_healthy

  fractal-uzh-converters:
    command: pixi run -e cli-client collect-fractal-uzh-converters
    description: "Trigger collection of fractal-uzh-converters"
    depends_on:
      fractal-server:
        condition: process_healthy
