[workspace]
authors = ["lorenzo <lorenzo.cerrone@uzh.ch>"]
channels = ["conda-forge"]
name = "fractal-pixi-compose"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[activation.env]
# postgres
PGDATA = "$PIXI_PROJECT_ROOT/local/postgres/data"
PGHOST = "localhost"
PGPORT = "5433"
# backend
POSTGRES_DB = "fractaldb"
POSTGRES_HOST = "localhost"
POSTGRES_USER = "fractal"
POSTGRES_PASSWORD = "fractal"
ADMIN_EMAIL = "admin@example.org"
ADMIN_PWD = "1234"
ADMIN_PROJECT_DIR = "$PIXI_PROJECT_ROOT/local/project_dir"
JWT_SECRET_KEY = "local-dev-secret-change-me"
FRACTAL_RUNNER_BACKEND = "local"
FRACTAL_DEFAULT_GROUP_NAME = "All"
JWT_EXPIRE_SECONDS = "84600"
FRACTAL_LOGGING_LEVEL = "20"
# frontend
FRACTAL_WEB_DIR = "$PIXI_PROJECT_ROOT/local/fractal-web"
FRACTAL_WEB_VERSION = "v1.24.0"
FRACTAL_SERVER = "http://localhost:8000"
FRACTAL_USER = "admin@example.org"
FRACTAL_PASSWORD = "1234"

[dependencies]
python = ">=3.13.0, <3.14.0"
nodejs = ">=24.0, <25.0"
postgresql = ">=18.0,<19.0"
process-compose = "*"

[pypi-dependencies]
fractal-server = "==2.20.1"
# fractal-server = {path = "../fractal-server", editable = true}
fractal-client = "==2.20.1"

[tasks.db-setup]
depends-on = ["db-cleanup"]
cmd = """
mkdir -p $PGDATA && \
initdb -D $PGDATA --no-locale --encoding=UTF8 --username=$POSTGRES_USER --auth=trust && \
pg_ctl -o '-p $PGPORT' -D $PGDATA -l $PIXI_PROJECT_ROOT/local/postgres/logfile start && \
createdb -p $PGPORT -h $POSTGRES_HOST -U $POSTGRES_USER $POSTGRES_DB
"""

[tasks.db-stop]
cmd = "pg_ctl -o '-p $PGPORT' status -D $PGDATA && pg_ctl -o '-p $PGPORT' -D $PGDATA stop || true"

[tasks.db-cleanup]
depends-on = ["db-stop"]
cmd = "rm -rf $PGDATA"

[tasks.backend-prepare-resource]
cmd = "python $PIXI_PROJECT_ROOT/scripts/build_resources.py"

[tasks.backend-set-db]
depends-on = ["db-setup", "backend-prepare-resource"]
cmd = "POSTGRES_PORT=$PGPORT fractalctl set-db"

[tasks.backend-setup]
depends-on = ["backend-set-db"]
cmd = """
POSTGRES_PORT=$PGPORT fractalctl init-db-data \
    --admin-email $ADMIN_EMAIL --admin-pwd $ADMIN_PWD \
    --admin-project-dir $ADMIN_PROJECT_DIR \
    --profile default \
    --resource $PIXI_PROJECT_ROOT/local/resources.json
"""

[tasks.backend-start]
cmd = "POSTGRES_PORT=$PGPORT fractalctl start --host 0.0.0.0 -p 8000"

[tasks.backend-cleanup]
cmd = "rm -rf local/data-jobs local/data-tasks"

[tasks.frontend-setup]
cmd = """
rm -rf $FRACTAL_WEB_DIR && \
mkdir -p $FRACTAL_WEB_DIR && \
git clone https://github.com/fractal-analytics-platform/fractal-web $FRACTAL_WEB_DIR && \
git -C $FRACTAL_WEB_DIR checkout $FRACTAL_WEB_VERSION && \
cd $FRACTAL_WEB_DIR && \
npm install
"""

[tasks.frontend-start]
cmd = "npm run dev --prefix $FRACTAL_WEB_DIR"

[tasks.frontend-cleanup]
cmd = "rm -rf $FRACTAL_WEB_DIR"

[tasks.setup]
depends-on = ["backend-setup", "frontend-setup"]

[tasks.cleanup]
depends-on = ["db-cleanup", "backend-cleanup", "frontend-cleanup"]


[tasks.collect-fractal-tasks-mock]
cmd = """
wget --quiet -O local/fractal_tasks_mock-0.0.1-py3-none-any.whl https://github.com/fractal-analytics-platform/fractal-server/raw/e0a3ca44f521fe622cf1d3a09d3e5058b096c6f2/tests/v2/fractal_tasks_mock/dist/fractal_tasks_mock-0.0.1-py3-none-any.whl && \
export FRACTAL_SERVER=$FRACTAL_SERVER && \
export FRACTAL_PASSWORD=$FRACTAL_PASSWORD && \
export FRACTAL_USER=$FRACTAL_USER && \
fractal task collect ./local/fractal_tasks_mock-0.0.1-py3-none-any.whl
"""
